[[islands]]
name = "Mainland"
vertices = [
    [0, 263], # North Point
    [220, 0], # East Point
    [235, -25], # by Hag Hut
    [273, -63],
    [439, -63],
    [439, -206],
    [165, -206], # Valsvig Shanty
    [109, -230], # shore by Elder Way / Timberhold crossroad
    [91, -248],
     #FIXME coast moves in?
    [91, -598], # SE corner where you can see mini swamp island

    [-80, -540], # West of smoke bridge
    [-80, -429], # West of Skjor's Landing
    [82, -429], # SE corner of Skjor's Bay
    [82, -325], # NE corner of Skjor's Bay
    # FIXME: add west peninsula from here
    [82, -137], # Timberhold
    [-264, -143], # SW point
    [-264, 263]
]

[[bases]]
name = "Last Resort"
point = [-10, 3]

[[bases]]
name = "Grig's Boulderheim"
point = [-2, -10]

[[bases]]
name = "Hrogden's Hrarbor"
point = [-20, -137]

[[bases]]
name = "Timberhold"
point = [82, -137]

[[bases]]
name = "Skjor's Landing"
point = [-38, -429]

[[bases]]
name = "Graveyard"
point = [35, 14]

[[bases]]
name = "Hrog's Den"
point = [117, -9]

[[bases]]
name = "Hag Hut"
point = [220, -25]

[[bases]]
name = "Smokehaus"
point = [15, -708] # FIXME

[[roads]] # Great Northern Path
points = [[0, 7], [0, 263]]

[[roads]] # Great Eastern Path
points = [[7, 0], [220, 0]]

[[roads]] # Great Southern Path
points = [
    [-5, -7],
    [-5, -137],
    [82, -137],
    [82, -325], # NE corner of Skjor's Bay
    [82, -429], # SE corner of Skjor's Bay
    [-38, -429]
]

[[roads]] # Great Western Path
points = [[-7, 0], [-264, 0]]

[[roads]] # Road to Smokehaus
points = [
    [-30, -429], # Intersection with road by Skjor's Landing
    [-30, -545], # North side of bridge
    [-33, -567], # South side of bridge
    [-23, -577],
    [-23, -708] # Smoke sign
]
