[[islands]]
name = "Mainland"
vertices = [
    [0, 263], # North Point
    [220, 263], # FIXME: Temporary for NE quadrant
    [220, 0], # East Point
    [235, -24], # by Hag Hut
    [272, -61], # [235, -25] -> [273, -63]
    [383, -61], # [273, -63] -> [439, -63]
    [383, -198], # [439, -63] -> [439, -206]
    #FIXME VERY IFFY AROUND HERE
    [120, -198], # Valsvig Shanty #jogsecs W: 274 to Valsvig Shanty   -> 263
    #FIXME: BEGIN NEED UPDATE
    #jogsecs SW: 26 -> 25
    [200, -248],
    #jogsecs S: 350 (this was like 30js inland most of the time, coast 30js to east)
    #  ^ This is a corner where you can see the mini swamp island
    #   -> 336
    [200, -540], # SE corner where you can see mini swamp island
    #FIXME: END NEED UPDATE
    [-80, -540], # West of smoke bridge
    [-80, -424], # West of Skjor's Landing
    [75, -424], # SE corner of Skjor's Bay
    [75, -325], # NE corner of Skjor's Bay
    [-38, -325], # NW corner of Skjor's Bay
    [82, -137], # Timberhold
    [-264, -143], # SW point
    [-264, 263]
]




[[bases]]
name = "Last Resort"
point = [-10, 3]

[[bases]]
name = "Grig's Boulderheim"
point = [-2, -10]

[[bases]]
name = "Hrogden's Hrarbor"
point = [-20, -137]

[[bases]]
name = "Timberhold"
point = [82, -137]

[[bases]]
name = "Skjor's Landing"
point = [-38, -429]

[[bases]]
name = "Graveyard"
point = [34, 13]

[[bases]]
name = "Hrog's Den"
point = [112, -9]

[[bases]]
name = "Hag Hut"
point = [220, -24]

[[bases]]
name = "Valsvig Shanty"
point = [120, -198]

[[bases]]
name = "Smokehaus"
point = [15, -708] # FIXME

[[bases]]
name = "The Elder"
point = [23, -500]

[[roads]] # Great Northern Path
points = [[0, 7], [0, 263]]

[[roads]] # Great Eastern Path
points = [[7, 0], [220, 0]]

[[roads]] # Great Southern Path
points = [
    [-5, -7],
    [-5, -137],
    [82, -137],
    [82, -325], # NE corner of Skjor's Bay
    [82, -429], # SE corner of Skjor's Bay
    [-38, -429]
]

[[roads]] # Great Western Path
points = [[-7, 0], [-264, 0]]

[[roads]] # Road to Smokehaus
points = [
    [-30, -429], # Intersection with road by Skjor's Landing
    [-30, -545], # North side of bridge
    [-33, -567], # South side of bridge
    [-23, -577],
    [-23, -708] # Smoke sign
]

[[roads]] # Smokehouse junction to Elder
points = [[-30, -500], [27, -500]] # FIXME: -500 was a guess